<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ATPU6BA" failures="2" tests="5" name="Test" time="0.213" errors="0" timestamp="2022-06-22T07:00:28 IST">
  <testcase classname="faildTC.NewFailTC" name="TC10" time="0.019"/>
  <testcase classname="faildTC.NewFailTC" name="TC6" time="0.112">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method faildTC.NewFailTC.TC6() didn&amp;apos;t finish within the time-out 100">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method faildTC.NewFailTC.TC6() didn't finish within the time-out 100
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC6 -->
  <testcase classname="faildTC.NewFailTC" name="TC7" time="0.003"/>
  <testcase classname="faildTC.NewFailTC" name="TC8" time="0.008">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at faildTC.NewFailTC.TC8(NewFailTC.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC8 -->
  <testcase classname="faildTC.NewFailTC" name="TC9" time="0.001"/>
</testsuite> <!-- Test -->
